---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ .Values.nodeName }}-etc
  namespace: {{ .Values.metadata.namespace }}
  {{- if .Values.pvc.annotations }}
  annotations:
{{ toYaml .Values.pvc.annotations | indent 8 }}
    {{- end }}
  labels:
    app.kubernetes.io/name: {{ .Values.nodeName }}-etc
    helm.sh/chart: {{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
    app.kubernetes.io/instance: {{ .Release.Name }}    
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: {{ .Values.storage.name }}
  resources:
    requests:
      storage: 256Mi

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ .Values.nodeName }}-logs
  namespace: {{ .Values.metadata.namespace }}
    {{- if .Values.pvc.annotations }}
  annotations:
{{ toYaml .Values.pvc.annotations | indent 8 }}
    {{- end }}
  labels:
    app.kubernetes.io/name: {{ .Values.nodeName }}-logs
    helm.sh/chart: {{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
    app.kubernetes.io/instance: {{ .Release.Name }}    
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: {{ .Values.storage.name }}
  resources:
    requests:
      storage: 5Mi

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ .Values.nodeName }}-h2
  namespace: {{ .Values.metadata.namespace }}
    {{- if .Values.pvc.annotations }}
  annotations:
{{ toYaml .Values.pvc.annotations | indent 8 }}
    {{- end }}
  labels:
    app.kubernetes.io/name: {{ .Values.nodeName }}-h2
    helm.sh/chart: {{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
    app.kubernetes.io/instance: {{ .Release.Name }}
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: {{ .Values.storage.name }}
  resources:
    requests:
      storage: 20Mi
