apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.nodeName }}
  namespace: {{ .Values.metadata.namespace }}
  labels:
    run: {{ .Values.nodeName }}
    app.kubernetes.io/name: {{ .Values.nodeName }}
    helm.sh/chart: {{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
    app.kubernetes.io/instance: {{ .Release.Name }}
spec:
  selector:
    app: {{ .Values.nodeName }}
  # we need healthCheckNodePort set to get rid of logs pollution
  {{- if (.Values.healthCheckNodePort) }}
  healthCheckNodePort: {{ .Values.healthCheckNodePort }}
  {{- end }}
  {{- if (.Values.service.type) }}
  type: {{ .Values.service.type }}
  {{- end }}
  ports:
    - port: {{ .Values.service.p2pPort }}
      targetPort: {{ .Values.service.p2pPort }}
      protocol: TCP
      name: http
    - port: {{ .Values.rpcSettingsAddressPort }} 
      targetPort: {{ .Values.rpcSettingsAddressPort }}
      protocol: TCP
      name: rpc
    - port: {{ .Values.service.sshdPort }} 
      targetPort: {{ .Values.service.sshdPort }}
      protocol: TCP
      name: ssh
