helm_templates:
  pki-generator: pki-generator.tpl
  signer: create_signer.tpl
  idman: idman.tpl
  nmap: nmap.tpl
corda_enterprise_image:
  cenm-networkmap-1.2: corda/enterprise-networkmap:1.2-zulu-openjdk8u242
