helm_templates:
  pki-generator: pki-generator.tpl
  signer: create_signer.tpl
  idman: idman.tpl
  nmap: nmap.tpl
  notary-initial-registration: notary_initial_registration.tpl
corda_enterprise_image:
  cenm-networkmap-1.2: corda/enterprise-networkmap:1.2-zulu-openjdk8u242
  cenm-notary-1.2: corda/notary:1.2-zulu-openjdk8u242
