# Default values for indy-auth-job.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

metadata:
  #Provide the namespace for organization's peer
  #Eg. namespace: baf
  namespace: baf

  #Provide the name for indy-auth-job release
  #Eg. name: indy-auth-job
  name: indy-auth-job

network:
  #Provide the name for network
  #Eg. name: baf
  name: baf

  #Provide the kubernetes host url
  #Eg. kubernetes_url: https://10.3.8.5:6443
  kubernetes_url: https://10.3.8.5:6443

image:
  #Provide the image name for the indy-auth-job container
  #Eg. name: indy-auth-job
  name: indy-auth-job

  #Provide the image repoitory for the indy-auth-job container
  #Eg. repository: alpine:3.9.4
  repository: alpine:3.9.4
 

vault:
  #Provide the vault server address
  #Eg. address: http://54.226.163.39:8200
  address: http://54.226.163.39:8200

  #Provide the vault key path
  #Eg. keyPath: provider.stewards
  keyPath: provider.stewards

  #Provide the vault identity
  #Eg. identity: my-identity
  identity: my-identity

  #Provide the admin authpath
  #Eg. admin_auth_path: kubernetes-baf-provider-admin-auth
  admin_auth_path: kubernetes-baf-provider-admin-auth

  #Provide the vault policy name
  #Eg. policy: baf-provider-steward-1-ro
  policy: baf-provider-steward-1-ro

  #Provide the vault policy content
  #Eg. policy_content: path "/kv/{{ organization }}/baf-ac/+/+/+/public*" {capabilities = [ "read", "list" ]}
  policy_content: path "/kv/{{ organization }}/baf-ac/+/+/+/public*" {capabilities = [ "read", "list" ]}

  #Provide the authpath
  #Eg. authpath: kubernetes-baf-provider-steward-1-auth
  auth_path: kubernetes-baf-provider-steward-1-auth

account:
  #Provide the admin service account name
  #Eg. admin_service: baf-provider-admin-vault-auth
  admin_service: baf-provider-admin-vault-auth

  #Provide the admin service account role
  #Eg. admin_role: rw
  admin_role: rw

  #Provide the service account name
  #Eg. service: provider-steward-1-vault-auth
  service: provider-steward-1-vault-auth

  #Provide the service account role
  #Eg. role: ro
  role: ro
